### ISSUE TITLE
#问题

### ISSUE THREAD

**Issue by huzai9527** [black-kyato/seu_net_verify#3]
- 校园网认证通过GET网址即可登陆
- 关键参数有三 **userid** 、**password** 、**user_ip**
- 只要获取user_ip 进行请求即可
- 在win下可以通过bat，双击运行脚本
- 在lin下可以通过sh脚本运行
- ipad登陆是个问题

**Comment by black-kyato** [comment]
是这样的，一开始写了mac地址，是因为正常登录发送的mac都是000000000000，故推测如果正常发送mac有可能实现无感登录。事实证明这个是校园网的认证服务器不行。原理都是类似的，只是没什么ios端开发经验。
